"does equipment wait time drive churn more than how often they attend?"

In [2]:
import pandas as pd

df = pd.read_csv("gym_churn_1M_dataset.csv")
df.head()

,Member_ID,Age,Gender,Membership_Type,Membership_Start_Date,Monthly_Fee,Monthly_Visits,Avg_Workout_Duration_Min,Peak_Hour_Preference,Cardio_Preference,Treadmill_Avg_Speed_Kmh,Treadmill_Avg_Incline_Pct,Group_Class_Attendance,PT_Session_Count,Supplement_Usage,Avg_Equipment_Wait_Time_Min,Late_Payment_Count,Profile_Type,Churn
0,1,17,Male,Premium,2025-08-20,74.61,10,76,Evening (17-21),Cycling,NaN,NaN,5,0,NaN,16.7,5,Casual,1
1,2,57,Male,Premium,2023-10-18,73.89,3,40,Evening (17-21),Treadmill,13.9,3.2,12,0,Full Stack,9.7,0,Drop-out,0
2,3,26,Female,Standard,2024-08-20,27.77,12,62,Late Night (21-24),Cycling,NaN,NaN,12,0,Whey Protein,23.0,6,Regular,0
3,4,25,Male,Standard,2024-01-28,28.90,5,58,Midday (10-14),Treadmill,8.7,12.1,11,0,Whey Protein,22.3,0,Casual,0
4,5,26,Male,Gold,2025-03-21,48.41,24,40,Late Night (21-24),Rowing,NaN,NaN,3,2,Pre-Workout,22.6,2,Casual,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 19 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Member_ID                    1000000 non-null  int64
 1   Age                          1000000 non-null  int64
 2   Gender                       1000000 non-null  object
 3   Membership_Type              1000000 non-null  object
 4   Membership_Start_Date        1000000 non-null  object
 5   Monthly_Fee                  1000000 non-null  float64
 6   Monthly_Visits               1000000 non-null  int64
 7   Avg_Workout_Duration_Min     1000000 non-null  int64
 8   Peak_Hour_Preference         1000000 non-null  object
 9   Cardio_Preference            773315 non-null   object
 10  Treadmill_Avg_Speed_Kmh      337598 non-null   float64
 11  Treadmill_Avg_Incline_Pct    337598 non-null   float64
 12  Group_Class_Attendance       1000000 non-null  int64
 13  PT_Session_Count             1000000 non-null  int64
 14  Supplement_Usage             580427 non-null   object
 15  Avg_Equipment_Wait_Time_Min  1000000 non-null  float64
 16  Late_Payment_Count           1000000 non-null  int64
 17  Profile_Type                 1000000 non-null  object
 18  Churn                        1000000 non-null  int64
dtypes: float64(4), int64(8), object(7)
memory usage: 145.0+ MB

Data Cleaning

1. Diagnosis before treatment

In [5]:
# Check for duplicated rows
df.duplicated().sum()

np.int64(0)

In [6]:
# Check stats on the variable needed for analysis
df[["Monthly_Visits", "Avg_Equipment_Wait_Time_Min"]].describe()

       Monthly_Visits  Avg_Equipment_Wait_Time_Min
count  1000000.000000               1000000.000000
mean         9.758237                    12.086831
std          6.760107                     7.441821
min          0.000000                     0.000000
25%          4.000000                     5.600000
50%          9.000000                    12.100000
75%         13.000000                    18.500000
max         28.000000                    25.000000